[package]
name = "blot-compiler"
version = "0.1.0"
edition = "2024"
publish = false

[features]
development-profile = []

[lib]
crate-type = ["cdylib"]

[dependencies]
num-bigint = { version = "=0.4.6", features = ["serde"] }
num-traits = "=0.2.19"
rmp-serde = "=1.3.0"
serde = { version = "=1.0.219", features = ["derive"] }
serde_json = { version = "=1.0.140", features = ["preserve_order"] }
wasm-encoder = "=0.255.0"
wasmparser = { version = "=0.255.0", default-features = false, features = ["simd"] }

[profile.release]
codegen-units = 1
lto = "fat"
opt-level = "s"
panic = "abort"
strip = true
