import { readSourceFixities } from "./source_fixities.ts";

const sourceRoots = ["compiler/src", "src"];
const sourceFiles: string[] = [];
for (const root of sourceRoots) await collect(root, sourceFiles);
sourceFiles.sort();

const diagnosticCodes = await tokens(
  sourceFiles.filter((path) => !path.endsWith(".generated.ts")),
  /BLOT_[A-Z][A-Z0-9_]+/g,
);
const intrinsicFiles = [
  "compiler/src/eval.rs",
  "compiler/src/hir.rs",
  "compiler/src/lower.rs",
  "compiler/src/primitives.rs",
  "compiler/src/typecheck.rs",
  "src/prelude/prelude.blot",
];
const intrinsics = await tokens(
  intrinsicFiles,
  /@[a-z_][A-Za-z0-9_]*(?:\.[a-z_][A-Za-z0-9_]*)*/g,
);
const operators = await readSourceFixities();
const protocol = JSON.parse(
  await Deno.readTextFile("compiler/protocol.json"),
) as Record<string, number>;
const prelude = await Deno.readTextFile("src/prelude/prelude.blot");
const preludeExports = exportsOfPrelude(prelude);
const focusedModules = [
  "array",
  "collections",
  "iter",
  "memory",
  "sort",
  "types",
];

const hotspots = await Promise.all(sourceFiles.map(async (path) => ({
  path,
  lines: lineCount(await Deno.readTextFile(path)),
})));
hotspots.sort((left, right) => {
  if (left.lines !== right.lines) return right.lines - left.lines;
  return left.path.localeCompare(right.path);
});

const health = `${
  JSON.stringify(
    {
      protocol,
      operators,
      diagnostics: diagnosticCodes,
      intrinsics,
      preludeExports,
      focusedModules,
      hotspots: hotspots.slice(0, 15),
    },
    null,
    2,
  )
}\n`;
const diagnosticSource =
  `// Generated by scripts/generate_language_health.ts. Do not edit.\n\n` +
  `export const diagnosticCodes = ${
    JSON.stringify(diagnosticCodes, null, 2)
  } as const;\n\n` +
  `export type DiagnosticCode = typeof diagnosticCodes[number];\n\n` +
  `const knownDiagnosticCodes = new Set<string>(diagnosticCodes);\n\n` +
  `export function isDiagnosticCode(value: string): value is DiagnosticCode {\n` +
  `  return knownDiagnosticCodes.has(value);\n` +
  `}\n`;
const stdlib = `# Standard library index\n\n` +
  `This file is generated from the exact public record returned by ` +
  `\`src/prelude/prelude.blot\`. The prelude remains ordinary Blot source; this ` +
  `index prevents its public surface from drifting invisibly.\n\n` +
  `Focused imports are available as ${
    focusedModules.map((name) => `\`blot:${name}\``).join(", ")
  }. They are ordinary source facades over the same prelude values.\n\n` +
  `| Export | Import |\n| --- | --- |\n` +
  preludeExports.map((name) => `| \`${name}\` | \`blot:prelude\` |`).join(
    "\n",
  ) +
  `\n`;

const outputs = [
  ["generated/language-health.json", health],
  ["src/diagnostic_codes.generated.ts", diagnosticSource],
  ["STDLIB.md", stdlib],
] as const;
for (const [path, expected] of outputs) {
  if (Deno.args.includes("--check")) {
    const actual = await Deno.readTextFile(path);
    if (actual !== expected) {
      throw new Error(`${path} is stale; run \`pnpm generate:health\``);
    }
    continue;
  }
  await Deno.writeTextFile(path, expected);
}

async function collect(root: string, files: string[]): Promise<void> {
  for await (const entry of Deno.readDir(root)) {
    const path = `${root}/${entry.name}`;
    if (entry.isDirectory) {
      if (entry.name !== "node_modules") await collect(path, files);
      continue;
    }
    if (entry.isFile && /\.(?:rs|ts|blot)$/.test(entry.name)) files.push(path);
  }
}

async function tokens(
  paths: readonly string[],
  pattern: RegExp,
): Promise<readonly string[]> {
  const found = new Set<string>();
  for (const path of paths) {
    const source = await Deno.readTextFile(path);
    for (const match of source.matchAll(pattern)) found.add(match[0]);
  }
  return [...found].sort();
}

function exportsOfPrelude(source: string): readonly string[] {
  const start = source.lastIndexOf("\nreturn {");
  if (start < 0) throw new Error("the prelude has no public return record");
  const names = [
    ...source.slice(start).matchAll(/^[ ]{2}\.([A-Za-z_][A-Za-z0-9_]*)\s*=/gm),
  ]
    .map((match) => match[1]);
  const unique = new Set(names);
  if (unique.size !== names.length) {
    throw new Error("the prelude public record has duplicate fields");
  }
  return names;
}

function lineCount(source: string): number {
  if (source.length === 0) return 0;
  return source.split("\n").length;
}
