import { readFile, writeFile } from "node:fs/promises";
import { resolve } from "node:path";
import { fileURLToPath, pathToFileURL } from "node:url";

interface ProtocolVersions {
  readonly compilerHostAbi: number;
  readonly checkedModuleCertificate: number;
  readonly runtimeHir: number;
}

interface CurrentInput {
  readonly schema: number;
  readonly publicAbi: { readonly major: number; readonly minor: number };
  readonly semanticCompiler: string;
  readonly emitter: string;
  readonly frontend: string;
  readonly productionBackend: string;
  readonly supportedPublicValues: readonly string[];
  readonly targetRestrictions: readonly string[];
  readonly editorFeatures: readonly string[];
  readonly latestBenchmarks: readonly string[];
}

interface CurrentImplementation extends CurrentInput, ProtocolVersions {}

const root = fileURLToPath(new URL("../", import.meta.url));
const inputPath = resolve(root, "compiler/current-implementation.json");
const protocolPath = resolve(root, "compiler/protocol.json");
const jsonPath = resolve(root, "generated/current-implementation.json");
const markdownPath = resolve(root, "generated/CURRENT_IMPLEMENTATION.md");

function stableJson(value: unknown): string {
  return `${JSON.stringify(value, null, 2)}\n`;
}

function bulletList(values: readonly string[]): string {
  return values.map((value) => `- ${value}`).join("\n");
}

function markdown(current: CurrentImplementation): string {
  return `<!-- Generated by scripts/generate_current_implementation.ts. Do not edit. -->
# Current implementation

| Contract | Current value |
| --- | --- |
| Semantic compiler | \`${current.semanticCompiler}\` |
| Frontend | \`${current.frontend}\` |
| Production backend | \`${current.productionBackend}\` |
| Emitter | \`${current.emitter}\` |
| Compiler-host ABI | ${current.compilerHostAbi} |
| Checked-module certificate | ${current.checkedModuleCertificate} |
| Runtime HIR | ${current.runtimeHir} |
| Public ABI | ${current.publicAbi.major}.${current.publicAbi.minor} |

## Supported public values

${bulletList(current.supportedPublicValues)}

## Deliberate target restrictions

${bulletList(current.targetRestrictions)}

## Editor features

${bulletList(current.editorFeatures)}

## Latest benchmark records

${bulletList(current.latestBenchmarks.map((path) => `[${path}](../${path})`))}
`;
}

async function readJson<T>(path: string): Promise<T> {
  return JSON.parse(await readFile(path, "utf8")) as T;
}

async function requireCurrent(path: string, expected: string): Promise<void> {
  let actual: string;
  try {
    actual = await readFile(path, "utf8");
  } catch {
    throw new Error(`${path} is missing; run pnpm current:generate`);
  }
  if (actual !== expected) {
    throw new Error(`${path} is stale; run pnpm current:generate`);
  }
}

async function validateCurrentClaims(
  current: CurrentImplementation,
): Promise<void> {
  if (current.productionBackend !== "direct-rust") return;
  const paths = [
    "README.md",
    "docs/compiler.md",
    "docs/backend.md",
    "docs/abi.md",
  ];
  for (const path of paths) {
    const source = await readFile(resolve(root, path), "utf8");
    if (/Gpupaper owns Core-to-Wasm planning/i.test(source)) {
      throw new Error(`${path} contradicts the direct Rust production backend`);
    }
  }
}

export async function generateCurrentImplementation(
  check: boolean,
): Promise<void> {
  const [input, protocol] = await Promise.all([
    readJson<CurrentInput>(inputPath),
    readJson<ProtocolVersions>(protocolPath),
  ]);
  const current: CurrentImplementation = { ...input, ...protocol };
  const json = stableJson(current);
  const md = markdown(current);
  await validateCurrentClaims(current);
  if (check) {
    await Promise.all([
      requireCurrent(jsonPath, json),
      requireCurrent(markdownPath, md),
    ]);
    return;
  }
  await Promise.all([
    writeFile(jsonPath, json),
    writeFile(markdownPath, md),
  ]);
}

if (import.meta.url === pathToFileURL(process.argv[1]).href) {
  generateCurrentImplementation(process.argv.includes("--check")).catch(
    (error: unknown) => {
      if (error instanceof Error) {
        console.error(error.message);
      } else {
        console.error(String(error));
      }
      process.exitCode = 1;
    },
  );
}
